### PR TITLE
Added benchmark for LinqToCsv

### PR DESCRIPTION
**Pull request by JoshClose**
Code is based off of section "Reading Raw Data Rows" https://www.codeproject.com/Articles/25133/LINQ-to-CSV-library#ReadingRawDataRows

### CODE REVIEW

**Comment by joelverhagen** [comment]
Looks like this one is also outputting data different:
```
 Group #1 (result JSON length = 921):
   - Csv
   - CsvHelper
   - CsvTextFieldParser
   - Ctl_Data
   - Cursively
   - FastCsvParser
   - FluentCsv
   - HomeGrown
   - LumenWorksCsvReader
   - mgholam_fastCSV
   - Microsoft_VisualBasic_FileIO_TextFieldParser
   - NReco_Csv
   - ServiceStack_Text
   - string_Split
   - SoftCircuits_CsvParser
   - Sylvan_Data_Csv
   - TinyCsvReader
 
 Group #2 (result JSON length = 939):
   - LinqToCsv
```

**Comment by JoshClose** [comment]
Is there a way to test this in your source? I'll make sure they are working with that check before making a pull request.

**Comment by joelverhagen** [comment]
My approach is to use the Test Explorer in Visual Studio. This will pop up the tests in the solution and you can run them there.

**Comment by JoshClose** [comment]
Oh, of course. lol Not sure what I was thinking.

**Comment by jzabroski** [comment]
Check encoding.

**Comment by JoshClose** [comment]
This library is returning `null` for empty strings.

**Comment by JoshClose** [comment]
Fixed.

**Comment by joelverhagen** [comment]
Awesome!

**Pull request merged**
