### PR TITLE
Added benchmark for ChoEtl

### PR DESCRIPTION
**Pull request by JoshClose**

### CODE REVIEW

**Comment by joelverhagen** [comment]
Looks like this one is reading data differently than the others. From the GitHub Actions build:
```
 Group #1 (result JSON length = 946233):
   - Csv
   - CsvHelper
   - CsvTextFieldParser
   - Ctl_Data
   - Cursively
   - FastCsvParser
   - FluentCsv
   - HomeGrown
   - LumenWorksCsvReader
   - mgholam_fastCSV
   - Microsoft_VisualBasic_FileIO_TextFieldParser
   - NReco_Csv
   - ServiceStack_Text
   - string_Split
   - SoftCircuits_CsvParser
   - Sylvan_Data_Csv
   - TinyCsvReader
 
 Group #2 (result JSON length = 963835):
   - ChoEtl
```

**Comment by JoshClose** [comment]
Hmm... Not sure what to do then. Do you want to include it and say it doesn't parse files correctly? I could have done something wrong in setting it up I guess, but it did make it through a benchmark run.

**Comment by jzabroski** [comment]
Could it be an encoding issue.

**Comment by JoshClose** [comment]
Fixed this one.

**Comment by joelverhagen** [comment]
Looks great, thanks!

**Pull request merged**
