### PR TITLE
Added benchmark for CommonLibrary.NET

### PR DESCRIPTION
**Pull request by JoshClose**

### CODE REVIEW

**Comment by JoshClose** [comment]
I don't get the failure locally.

image

**Comment by joelverhagen** [comment]
Works locally for me too. I'll merge and figured out what's up.

**Comment by joelverhagen** [comment]
Okay, it looks like the CI was running on `ubuntu-latest` and I presume we are both using Windows. Probably line ending issues.

**Comment by JoshClose** [comment]
Does that mean your tests need to specify the line ending? Libraries should be able to to handle any type of newline, but tests should also be consistent across platforms.

**Comment by joelverhagen** [comment]
> Does that mean your tests need to specify the line ending?

Yes 😞. I had to make this change. Previously it was using `Environment.NewLine` which yielded `\n` on Ubuntu leading to the test failure.

https://github.com/joelverhagen/NCsvPerf/blob/f59ab5ba27d4b9e1c3a4f3a4477b02f0bb801b37/NCsvPerf/TestData/TestData.cs#L69-L72

> Libraries should be able to to handle any type of newline, but tests should also be consistent across platforms.

I looked through the CommonLibrary.NET source code on CodePlex and found code detecting newline by explicitly checking for CR LF (`\r` then `\n`). This means it does not handle any type of newline.

As a side not the SEA.CommonLibrary.NET package is compiled with Debug configuration. I'm considering forking the source code onto GitHub myself and publishing my own copy with at least Release configuration and perhaps even a minimal change to handle files with just LF.

**Comment by JoshClose** [comment]
Nice. What a good open source citizen.

**Comment by joelverhagen** [comment]
Done.

[GitHub](https://github.com/joelverhagen/Knapcode.CommonLibrary.NET) | [NuGet](https://www.nuget.org/packages/Knapcode.CommonLibrary.NET)

LF is supported and it's built with Release configuration.

**Comment by JoshClose** [comment]
Awesome! In your NuGet description you might want to mention that your version supports LF and is in Release config.

**Pull request merged**
